
import Provider from "@/components/Provider";
import '../styles/globals.css'
import Navbar from "@/components/Nav";

export const metadata = {
  title: "Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-anuphan">
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <div className="relative z-10">
            <main className="app">
              <Navbar />
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}