
import '../styles/globals.css'
import Provider from "@/components/Provider";
import Navbar from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Mor Lam Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-anuphan">
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <div className="relative z-10">
            <main className="app">
              <Navbar />
              {children}
              <Footer/>
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}